package main

// Pixel art for the example games, drawn as ASCII grids. Runes map to
// the shared palette in art.go; space is transparent. Keeping the art
// as text means a sprite change is a text edit plus `go run
// ./tools/genassets`, with no binary files to hand-edit.

// --- characters ---

// hero: a small adventurer, two-frame walk cycle. Used by the top-down
// games (arena, gem rush, caves, dungeon).
var heroWalk = [][]string{
	{
		"    BBBB    ",
		"   BBBBBB   ",
		"   BFFFFB   ",
		"   FFFFFF   ",
		"   FDFFDF   ",
		"   FFFFFF   ",
		"    FFFF    ",
		"   BBBBBB   ",
		"  BBBCCBBB  ",
		"  FBBCCBBF  ",
		"  FBBBBBBF  ",
		"   BBBBBB   ",
		"   BB  BB   ",
		"   TT  TT   ",
		"  TTT  TTT  ",
		"            ",
	},
	{
		"    BBBB    ",
		"   BBBBBB   ",
		"   BFFFFB   ",
		"   FFFFFF   ",
		"   FDFFDF   ",
		"   FFFFFF   ",
		"    FFFF    ",
		"   BBBBBB   ",
		"  BBBCCBBB  ",
		"  FBBCCBBF  ",
		"  FBBBBBBF  ",
		"   BBBBBB   ",
		"  BB    BB  ",
		"  TT    TT  ",
		" TTT    TTT ",
		"            ",
	},
}

// zombie: shambling green figure, two-frame lurch.
var zombieWalk = [][]string{
	{
		"    GGGG    ",
		"   GGGGGG   ",
		"   GhGGhG   ",
		"   GGGGGG   ",
		"   GRGGRG   ",
		"    GGGG    ",
		"   gGGGGg   ",
		"  ggGGGGgg  ",
		"  hgGGGGgh  ",
		"  h GGGG h  ",
		"    GGGG    ",
		"    GGGG    ",
		"   gg  gg   ",
		"   gg  gg   ",
		"  ggg  ggg  ",
		"            ",
	},
	{
		"            ",
		"    GGGG    ",
		"   GGGGGG   ",
		"   GhGGhG   ",
		"   GGGGGG   ",
		"   GRGGRG   ",
		"    GGGG    ",
		"  hgGGGGgh  ",
		"  hgGGGGgh  ",
		"   gGGGGg   ",
		"    GGGG    ",
		"    GGGG    ",
		"    gggg    ",
		"   gg  gg   ",
		"  ggg   gg  ",
		"            ",
	},
}

// runner: side-view sprinter, four-frame run cycle.
var runnerRun = [][]string{
	{
		"     BBBB     ",
		"    BFFFFB    ",
		"    FFDFFF    ",
		"     FFFF     ",
		"    RRRRRR    ",
		"   RRRRRRRR   ",
		"  F RRRRRR F  ",
		"  F RRRRRR F  ",
		"    RRRRRR    ",
		"    bb  bb    ",
		"   bb    bb   ",
		"  bb      bb  ",
		"  TT      TT  ",
		" TTT      TTT ",
	},
	{
		"     BBBB     ",
		"    BFFFFB    ",
		"    FFDFFF    ",
		"     FFFF     ",
		"    RRRRRR    ",
		"   RRRRRRRR   ",
		"    RRRRRR F  ",
		"  F RRRRRR F  ",
		"    RRRRRR    ",
		"    bbbbbb    ",
		"    bb  bb    ",
		"   bb    bb   ",
		"   TT    TT   ",
		"  TTT    TTT  ",
	},
	{
		"     BBBB     ",
		"    BFFFFB    ",
		"    FFDFFF    ",
		"     FFFF     ",
		"    RRRRRR    ",
		"   RRRRRRRR   ",
		"  F RRRRRR F  ",
		"  F RRRRRR F  ",
		"    RRRRRR    ",
		"    bb  bb    ",
		"     bbbb     ",
		"     bbbb     ",
		"    TT  TT    ",
		"   TTT  TTT   ",
	},
	{
		"     BBBB     ",
		"    BFFFFB    ",
		"    FFDFFF    ",
		"     FFFF     ",
		"    RRRRRR    ",
		"   RRRRRRRR   ",
		"  F RRRRRR    ",
		"  F RRRRRR F  ",
		"    RRRRRR    ",
		"    bbbbbb    ",
		"   bb    bb   ",
		"  bb      bb  ",
		"  TT      TT  ",
		" TTT      TTT ",
	},
}

// runner jumping: tucked legs, two-frame bob.
var runnerJump = [][]string{
	{
		"     BBBB     ",
		"    BFFFFB    ",
		"    FFDFFF    ",
		"     FFFF     ",
		"  F RRRRRR    ",
		" FF RRRRRRRR  ",
		"    RRRRRR FF ",
		"    RRRRRR  F ",
		"    RRRRRR    ",
		"    bbbbbb    ",
		"   bb    bb   ",
		"   TT    TT   ",
		"              ",
		"              ",
	},
	{
		"              ",
		"     BBBB     ",
		"    BFFFFB    ",
		"    FFDFFF    ",
		"     FFFF     ",
		"  F RRRRRR    ",
		" FF RRRRRRRR  ",
		"    RRRRRR FF ",
		"    RRRRRR  F ",
		"    RRRRRR    ",
		"    bbbbbb    ",
		"   bb    bb   ",
		"   TT    TT   ",
		"              ",
	},
}

// runner death: crumple and fade.
var runnerDeath = [][]string{
	{
		"              ",
		"     BBBB     ",
		"    BFFFFB    ",
		"    FFRFFF    ",
		"     FFFF     ",
		"   RRRRRRRR   ",
		"  RRRRRRRRRR  ",
		"   RRRRRRRR   ",
		"    bbbbbb    ",
		"  bb      bb  ",
		"  TT      TT  ",
		"              ",
		"              ",
		"              ",
	},
	{
		"              ",
		"              ",
		"              ",
		"   BB  FFFF   ",
		"  RRRRRRRRRR  ",
		" RRRRRRRRRRRR ",
		"  RRRRRRRRRR  ",
		"  bbbb  bbbb  ",
		" TT        TT ",
		"              ",
		"              ",
		"              ",
		"              ",
		"              ",
	},
	{
		"              ",
		"              ",
		"              ",
		"              ",
		"              ",
		"  s  ssss  s  ",
		" ss RRRRRR ss ",
		"  ssssssss    ",
		"   ss    ss   ",
		"              ",
		"              ",
		"              ",
		"              ",
		"              ",
	},
	{
		"              ",
		"              ",
		"              ",
		"      ss      ",
		"   s      s   ",
		"      ss      ",
		"  s        s  ",
		"     ssss     ",
		"              ",
		"              ",
		"              ",
		"              ",
		"              ",
		"              ",
	},
}

// --- pickups and props ---

// coin: spinning gold, four frames.
var coinSpin = [][]string{
	{
		"   YYYY   ",
		"  YYYYYY  ",
		" YYyyyyYY ",
		" YYyWWyYY ",
		" YYyWWyYY ",
		" YYyyyyYY ",
		"  YYYYYY  ",
		"   YYYY   ",
	},
	{
		"    YY    ",
		"   YYYY   ",
		"   YyyY   ",
		"   YyWY   ",
		"   YyWY   ",
		"   YyyY   ",
		"   YYYY   ",
		"    YY    ",
	},
	{
		"    yy    ",
		"    yy    ",
		"    yy    ",
		"    yW    ",
		"    yW    ",
		"    yy    ",
		"    yy    ",
		"    yy    ",
	},
	{
		"    YY    ",
		"   YYYY   ",
		"   YyyY   ",
		"   YWyY   ",
		"   YWyY   ",
		"   YyyY   ",
		"   YYYY   ",
		"    YY    ",
	},
}

// gem: faceted crystal, two-frame sparkle.
var gemSparkle = [][]string{
	{
		"   CCCC   ",
		"  CCWWCC  ",
		" CCWWWWCC ",
		"CCWWCCWWCC",
		" CCWWWWCC ",
		"  CCWWCC  ",
		"   CCCC   ",
		"    CC    ",
	},
	{
		"   CCCC   ",
		"  CCCCCC  ",
		" CCCWWCCC ",
		"CCCWWWWCCC",
		" CCCWWCCC ",
		"  CCCCCC  ",
		"   CCCC   ",
		"    CC    ",
	},
}

var keyArt = []string{
	"  YYYY  ",
	" YY  YY ",
	" YY  YY ",
	"  YYYY  ",
	"   YY   ",
	"   YYY  ",
	"   YY   ",
	"   YYY  ",
}

var chestArt = []string{
	"            ",
	"  YYYYYYYY  ",
	" YyyyyyyyyY ",
	" YyTTTTTTyY ",
	" YyTTTTTTyY ",
	"  YYYYYYYY  ",
	" TTTTYYTTTT ",
	" TTTTYYTTTT ",
	" TTTTYYTTTT ",
	" TTTTTTTTTT ",
	"  TTTTTTTT  ",
	"            ",
}

var doorArt = []string{
	"oooooooooooo",
	"oOOOOOOOOOOo",
	"oOTTTTTTTTOo",
	"oOTTTTTTTTOo",
	"oOTTTTYYTTOo",
	"oOTTTTYYTTOo",
	"oOTTTTTTTTOo",
	"oOTTTTTTTTOo",
	"oOTTTTTTTTOo",
	"oOTTTTTTTTOo",
	"oOOOOOOOOOOo",
	"oooooooooooo",
}

var spikeArt = []string{
	"  W    W    W   ",
	"  W    W    W   ",
	" WWW  WWW  WWW  ",
	" WsW  WsW  WsW  ",
	" WsW  WsW  WsW  ",
	"WsssWWsssWWsssW ",
	"SSSSSSSSSSSSSSSS",
	"SSSSSSSSSSSSSSSS",
}

var crateArt = []string{
	"TTTTTTTTTT",
	"TuuuuuuuuT",
	"TuTTTTTTuT",
	"TuTuuuuTuT",
	"TuTuuuuTuT",
	"TuTuuuuTuT",
	"TuTTTTTTuT",
	"TuuuuuuuuT",
	"TTTTTTTTTT",
	"TTTTTTTTTT",
}

// --- projectiles and effects ---

var bulletArt = []string{
	" YY ",
	"YWWY",
	"YWWY",
	" YY ",
}

// boom: four-frame explosion, shared by several games.
var boomFrames = [][]string{
	{
		"                ",
		"                ",
		"                ",
		"                ",
		"                ",
		"                ",
		"       YY       ",
		"      YWWY      ",
		"      YWWY      ",
		"       YY       ",
		"                ",
		"                ",
		"                ",
		"                ",
		"                ",
		"                ",
	},
	{
		"                ",
		"                ",
		"                ",
		"                ",
		"      YYYY      ",
		"     YOOOOY     ",
		"    YOWWWWOY    ",
		"    YOWWWWOY    ",
		"    YOWWWWOY    ",
		"     YOOOOY     ",
		"      YYYY      ",
		"                ",
		"                ",
		"                ",
		"                ",
		"                ",
	},
	{
		"                ",
		"     O    O     ",
		"    O OOOO O    ",
		"   O OYYYYO O   ",
		"     OYOOYO     ",
		"   O YO  OY O   ",
		"    OY    YO    ",
		"   O Y    Y O   ",
		"    OY    YO    ",
		"   O YO  OY O   ",
		"     OYOOYO     ",
		"   O OYYYYO O   ",
		"    O OOOO O    ",
		"     O    O     ",
		"                ",
		"                ",
	},
	{
		"                ",
		"                ",
		"   s       s    ",
		"                ",
		"      s  s      ",
		"                ",
		"  s    s     s  ",
		"                ",
		"     s    s     ",
		"                ",
		"  s     s    s  ",
		"                ",
		"       s        ",
		"                ",
		"                ",
		"                ",
	},
}

// --- paddle games ---

var paddleArt = []string{
	"WWWWWWWWWWWWWWWWWWWW",
	"WwwwwwwwwwwwwwwwwwwW",
	"WwCCCCCCCCCCCCCCCCwW",
	"WwCCCCCCCCCCCCCCCCwW",
	"WwwwwwwwwwwwwwwwwwwW",
	"WWWWWWWWWWWWWWWWWWWW",
}

var paddleVArt = []string{
	"WWWWWW",
	"WwwwwW",
	"WwCCwW",
	"WwCCwW",
	"WwCCwW",
	"WwCCwW",
	"WwCCwW",
	"WwCCwW",
	"WwCCwW",
	"WwCCwW",
	"WwwwwW",
	"WWWWWW",
}

var ballArt = []string{
	" WWWW ",
	"WWWWWW",
	"WWWWww",
	"WWwwww",
	"WwwwwW",
	" wwww ",
}

// brick: one shape, recolored per row by swapping the palette rune.
func brickArt(fill, light, dark rune) []string {
	return []string{
		string([]rune{light, light, light, light, light, light, light, light, light, light, light, light}),
		string([]rune{light, fill, fill, fill, fill, fill, fill, fill, fill, fill, fill, dark}),
		string([]rune{light, fill, fill, fill, fill, fill, fill, fill, fill, fill, fill, dark}),
		string([]rune{light, fill, fill, fill, fill, fill, fill, fill, fill, fill, fill, dark}),
		string([]rune{dark, dark, dark, dark, dark, dark, dark, dark, dark, dark, dark, dark}),
	}
}

// --- memory game card faces ---

var cardBack = []string{
	"dddddddddddd",
	"dccccccccccd",
	"dcddddddddcd",
	"dcdBBddBBdcd",
	"dcdBBddBBdcd",
	"dcddddddddcd",
	"dcdBBddBBdcd",
	"dcdBBddBBdcd",
	"dcddddddddcd",
	"dcccccccccdd",
	"dddddddddddd",
	"dddddddddddd",
}

var cardFaces = [][]string{
	{ // heart
		"WWWWWWWWWWWW",
		"W          W",
		"W  RR  RR  W",
		"W RRRRRRRR W",
		"W RRRRRRRR W",
		"W  RRRRRR  W",
		"W   RRRR   W",
		"W    RR    W",
		"W          W",
		"W          W",
		"W          W",
		"WWWWWWWWWWWW",
	},
	{ // star
		"WWWWWWWWWWWW",
		"W          W",
		"W    YY    W",
		"W   YYYY   W",
		"W YYYYYYYY W",
		"W  YYYYYY  W",
		"W  YYYYYY  W",
		"W YY    YY W",
		"W          W",
		"W          W",
		"W          W",
		"WWWWWWWWWWWW",
	},
	{ // moon
		"WWWWWWWWWWWW",
		"W          W",
		"W   CCCC   W",
		"W  CC  CC  W",
		"W CC    CC W",
		"W CC       W",
		"W CC    CC W",
		"W  CC  CC  W",
		"W   CCCC   W",
		"W          W",
		"W          W",
		"WWWWWWWWWWWW",
	},
	{ // leaf
		"WWWWWWWWWWWW",
		"W          W",
		"W     GG   W",
		"W   GGGGG  W",
		"W  GGGGGGG W",
		"W  GGGgGGG W",
		"W  GGgGGG  W",
		"W   ggGG   W",
		"W    g     W",
		"W          W",
		"W          W",
		"WWWWWWWWWWWW",
	},
	{ // drop
		"WWWWWWWWWWWW",
		"W          W",
		"W    BB    W",
		"W    BB    W",
		"W   BBBB   W",
		"W  BBBBBB  W",
		"W  BBCCBB  W",
		"W  BBBBBB  W",
		"W   BBBB   W",
		"W          W",
		"W          W",
		"WWWWWWWWWWWW",
	},
	{ // bolt
		"WWWWWWWWWWWW",
		"W          W",
		"W     YY   W",
		"W    YY    W",
		"W   YY     W",
		"W  YYYYY   W",
		"W    YY    W",
		"W   YY     W",
		"W  YY      W",
		"W          W",
		"W          W",
		"WWWWWWWWWWWW",
	},
	{ // gear
		"WWWWWWWWWWWW",
		"W          W",
		"W   ssss   W",
		"W  ssssss  W",
		"W ss sSs ss W"[:12],
		"W ss SSS ss W"[:12],
		"W  ssssss  W",
		"W   ssss   W",
		"W          W",
		"W          W",
		"W          W",
		"WWWWWWWWWWWW",
	},
	{ // flower
		"WWWWWWWWWWWW",
		"W          W",
		"W    kk    W",
		"W  kkkkkk  W",
		"W  kkYYkk  W",
		"W kkYYYYkk W",
		"W  kkYYkk  W",
		"W  kkkkkk  W",
		"W    gg    W",
		"W    gg    W",
		"W          W",
		"WWWWWWWWWWWW",
	},
}

// --- dialog portraits ---

var elderArt = []string{
	"    WWWWWWWW    ",
	"   WWmmmmmmWW   ",
	"  WmmmmmmmmmmW  ",
	"  WmmFFFFFFmmW  ",
	"  WmFFFFFFFFmW  ",
	"  WFFDFFFFDFFW  ",
	"  WFFFFFFFFFFW  ",
	"  WFFFFwwFFFFW  ",
	"  WFFFwwwwFFFW  ",
	"  WWFFwwwwFFWW  ",
	"   WWwwwwwwWW   ",
	"  WWwwwwwwwwWW  ",
	" WWwwwwwwwwwwWW ",
	" WmmwwwwwwwwmmW ",
	" WmmmmwwwwmmmmW ",
	"  WWmmmmmmmmWW  ",
}

var heroArt = []string{
	"    BBBBBBBB    ",
	"   BBBBBBBBBB   ",
	"  BBBFFFFFFBBB  ",
	"  BBFFFFFFFFBB  ",
	"  BFFFFFFFFFFB  ",
	"  BFFDFFFFDFFB  ",
	"  BFFFFFFFFFFB  ",
	"  BFFFFFFFFFFB  ",
	"  BFFFRRRRFFFB  ",
	"  BBFFFFFFFFBB  ",
	"   BBFFFFFFBB   ",
	"  BBBBBBBBBBBB  ",
	" BBBBBCCCCBBBBB ",
	" BBBBBCCCCBBBBB ",
	" BBBBBBBBBBBBBB ",
	"  BBBBBBBBBBBB  ",
}
